### ISSUE TITLE
Investigate whether segyio Group class can be used to speed up reading (non-3d) data.

### ISSUE THREAD

**Issue by trhallam** [trhallam/segysak#57]
segyio added a file accessor called Groups which can be used to access traces common header key values.

```
with segyio.open('file.segy') as f:
    g = f.group([keys...])
    for h in g[[keys...]].header:
        print(h)
```

**Comment by fr1ll** [comment]
What can I do to help with this? As an outcome, would you want a documentation example, or something else? I already have a variety of publicly available shot-ordered data on disk at the moment that I had planned to test reading into `segyio`.

**Comment by trhallam** [comment]
Hi @fr1ll , there are functions to read pre-stack data into netcdf and xarray here
https://github.com/trhallam/segysak/blob/fe42e8ccf28463454ecd24cee3d75093518930a2/segysak/segy/_segy_loader.py#L194-L203
and here
https://github.com/trhallam/segysak/blob/fe42e8ccf28463454ecd24cee3d75093518930a2/segysak/segy/_segy_loader.py#L321-L328

Currently, these work by scanning trace headers first and then using that scan to load the data trace by trace. I don't think we can get around scanning the headers to build an appropriate sized array but we might be able to speed up the transfer from segy into netcdf or xarray which is currently trace by trace if we use a combination of the scanned headers and the `segyio` Group class,

If you have other ideas for optimisation I'd be keen to hear them as well.

**Comment by fr1ll** [comment]
@trhallam thanks for the details. I need to look at `Group` a bit and try it out, but I think it makes sense to me... The user could specify a number of sort keys, then `segysak` can scan the trace headers and determine the maximum size of an array. (Since `Group` is just a dict, that's just the maximum size of a value of the dict.)

We can expect that most arrays will not be the maximum size--just like the [example in `segyio`](https://github.com/equinor/segyio/blob/158b174b74dac47b36c367d038387f11f49b44c4/python/segyio/gather.py#L259). If internally there are 100 traces in the largest array, numbered 1 - 100, there may be some arrays with only traces 5 - 93 and a gap in the middle as well. Do you know if this is going to be a problem for `xarray`? I had been thinking it expects evenly spaced labels to be present.

**Comment by trhallam** [comment]
So `xarray` basically supports any number of orthogonal axes which are usually sequential and 1 dimensional. They can be but don't have to be equispaced. For the purposes of seismic data, these means that empty traces must still be filled with at least NaN because as far as I know, `xarray` doesn't support partial population of data along dimensions. This is kind of why we have a trace by trace approach to conversion into NetCDF at the moment but what I am hoping is that by using the group function we can load data into memory in larger groups, check if it is the right shape and dump it out if it is, else we might then have to still iterate trace by trace to find where the gaps are.

**Comment by fr1ll** [comment]
I'd say most field data will have gaps, but there will still be a regular numbering scheme. I think `segysak` could still read in as groups with a tolerance for how many NaNs to create. Something like this:

1. Compute the set of values for each axis
2. Compute all the combinations of these values
3. Determine how many of these combinations are missing from the input -- i.e. how many NaNs you'd create if reading in by groups
4. Use some kind of "max new NaNs" criterion (a user parameter) to determine how to proceed
    - Criterion is `None` --> read-trace-by-trace, no new NaNs
    - Ratio of NaNs : input traces  >  criterion --> read trace-by-trace, no new NaNs
    - Ratio of NaNs : input traces =< criterion --> read in as groups, create the NaNs

It would need to handle duplicate input traces per combination of axis values. It could catch this in the headers scan as well -- if there were duplicates, create an additional axis incrementing from 0 to the max number of duplicates for any combination. The ordering of this axis could preserve the input ordering of the traces.

What do you think?

**Comment by trhallam** [comment]
Generally I think this sounds OK. I feel like it might not fit into the current segysak `segy_loader` function very easily though. We should probably consider creating a special loader function for shot-gathers because these are quite a specific data type which differ a lot from processed products which are what we have focused on so far. We also need to work out how you are doing to label dimensions, particularly if you have dynamic dimensions for duplicated traces. Currently we use the dimensions names ['cdp', 'iline', 'xline', 'twt' 'depth' & 'offset'] but these may not be appropriate fro shot gathers which are more like ['shot_line', 'receiver_line', 'station', 'streamer'] and so on.

I'd start by using the `segy_header_scrape` function on your data and then implementing your geometry builder from that. You basically have to pre-build the geometry form scratch with `xarray`. Although, there are options to extend dimensions but I don't know if that is a good idea. Once you have the geometry worked out and saved to disk you can then use the streaming techniques I have implemented for other segy geometries to avoid loading the full volume into memory before saving it out. This is where your optimisations should come in to improve through put.

Do you want to give it a go and we can talk about the results or any issues as they arise?

**Comment by fr1ll** [comment]
Yeah sounds great! This should be enough to start hacking around with it.

**Comment by fr1ll** [comment]
I've been thinking about this a bit more as I've been reading in some OBN data. I'd say it's a pretty common situation that your gather key (something like 'shot_number') increments irregularly. You might have an increment of 3 for part of the line, then 4 for other parts... You might have something even stranger than that. Lots of seismic data is locked up in SEG-Y's with irregular schemes like that... Hard to say what percentage, but it accounts for >half than the seismic I've dealt with.

It seems like there's two basic ways to smash this into a regular grid format like `xarray` / `netcdf`

1. You find the `shot_num' increment that will create the fewest number of dead traces. In the case that you sometimes increment by 3 and sometimes by 4, you have to go with an increment of 1 and you have an alarming number of dead traces.
2. You take the set of all `shot_nums` and make some kind of mapping to their index in that set. So if your shot nums look like [1003, 1007, 1011, 1012,... ] you might have to carry a dict that looks like {0: 1003, 1: 1007, 2: 1011, 3: 1012...}. This is a pain because it means you have to have a wrapper for xarray -- which maybe you already have for the 3D seismic case?

What do you think? Would it help to talk through examples via swung-call?

**Comment by trhallam** [comment]
Hi @fr1ll let's definitely have a chat soon. I appreciate you looking into this.

One way around the dead trace issue might be to use sparse representations using:

- https://sparse.pydata.org/en/latest/index.html , and
- https://github.com/pydata/xarray/issues/3213, it looks like `xarray` will support or already supports these. This could significantly reduce memory/disk usage without needing to worry too much about a mapping.

If you think mappings are a better option then we would probably need to write a custom accessor for `xarray` as we have already done for the basic seisnc class. I'm not completely opposed to this but it would take a fair bit of work and possibly require quite a bit of maintenance to keep up-to-date with `xarray`. I suspect this would also be quite slow.

When are you free for a call? Hit me up in slack I'm around most of the time.

**Comment by trhallam** [comment]
Going to ignore this from `segyio` as it isn't helpful. The segy_freewriter fixes some of the chunking issues.
Look towards using `sparse` package COO structure for irregularly sampled data.
