### ISSUE TITLE
fail to convert a 2D sgy file into dataframe

### ISSUE THREAD

**Issue by JayFu** [trhallam/segysak#93]
thanks for the barvo job.

I got a 77.9 MB sgy file and I was trying to open it as doc **_Vectorisation_**  goes.

But it seemed that python was killed due to memory issue.

Here is the lines.

`from segysak.segy import segy_loader, well_known_byte_locs, segy_writer

volve_3d_path = pathlib.Path("./2dshot.sgy")

volve_3d = segy_loader(volve_3d_path, **well_known_byte_locs("petrel_3d"))

100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 24.0k/24.0k [00:02<00:00, 8.30k traces/s]
Loading as 3D
Fast direction is CDP
Converting SEGY: 100%|███████████████████████████████████████████████████████████████████████████████████| 24.0k/24.0k [00:12<00:00, 1.93k traces/s]

volve_3d_df = volve_3d.to_dataframe()
[1]    40544 killed     python`

**Comment by trhallam** [comment]
Hi @JayFu , you will need to change the arguments to `segy_loader` so that the data is imported as 2d. 

From the file name I assume that the data is 2d shot gathers so you will need to specify the byte locations for the cdp numbering and the offset.

Use the function `segy_header_scan` to work out which bytes contain the appropriate header information.
```
shot2d = segy_loader("./2dshot.sgy", cdp=21, offset=37)
```

**Comment by JayFu** [comment]
This help a lot, thanks!

I am new to seismic data because of work. I think I should go to read some seismic introduction.

I close this Issue, thank you for the help
